In [1]:
#1. Write a function so that the columns of the output matrix are powers of the input vector.

import numpy as np

# Define the function
def Vandermonde(x,N):
    result = np.column_stack([x**(N-1-i) for i in range (N)])
    return result

# invoke the function
x = np.array([1, 2, 3, 5])
N=3
y = Vandermonde(x,N)
print(y)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]


In [4]:
#2. Write a function to find moving average in an array over a window:
#Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

import numpy as np
import pandas as pd

# define teh funcation
def moving_average(arr,n):

    # convert the array to a series so that rolling funcation can be applied.
    x = pd.Series(arr)
    y = x.rolling(window=n,center=True).mean()
    z = y.dropna()
    return z.values

inp_arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window = 3

result = moving_average(inp_arr,window)
result

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])